### ISSUE TITLE
New Comments not adding to UI in Side Comment Modal

### ISSUE THREAD

**Issue by FalconRam** [FalconRam/mern-connectit_v2#6]
New Comments added from the not  Side Comment Modal is adding to UI in Side Comment Modal neither after submits nor api responded.

![image](https://github.com/FalconRam/mern-connectit_v2/assets/50442304/c9eb1cec-e3c5-4cfa-b0f7-1d020198b737)

**Comment by ennanuel** [comment]
Does your frontend send a request to the API for the new comments when you create a new comment?

**Comment by FalconRam** [comment]
> Does your frontend send a request to the API for the new comments when you create a new comment?

Yes, it does. Thanks for time. The Issue is fixed. Feel free to look into the fix added.
